New errors, TypeError: 'numpy.float64' object does not support item assignment
  File "Game.py", line 63, in Policy
    x[int(np.argmax(x))] = int((np.min(x)-1))
TypeError: 'numpy.float64' object does not support item assignment